Task4_1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Task4_1_app.urls', namespace='app'))
]

Task4_1_app/urls.py
from django.urls import path
from . import views


app_name = 'app'


urlpatterns = [
    path('', views.home, name='home'),
    path('teachers/', views.teacher, name='teachers'),
    path('class_details/', views.class_detail, name='class_details'),
    path('students/', views.student, name='students'),
    path('adult_student/', views.adult_student, name='adult_students'),
    path('young_students/', views.young_student, name='young_students'),
]

Task4_1_app/models.py
from django.db import models


class Person(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)

    class Meta:
        abstract = True

    def __str__(self):
        full_name = f'{self.first_name} {self.last_name}'
        return full_name


class Teacher(Person):
    subject = models.CharField(max_length=100)


class ClassDetails(models.Model):
    name = models.CharField(max_length=100)
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Student(Person):
    class_details = models.ForeignKey(ClassDetails, on_delete=models.CASCADE)
    age = models.IntegerField()
    attendance = models.IntegerField()


class AdultStudentManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(age__gte=18)


class AdultStudent(Student):
    object = AdultStudentManager()

    class Meta:
        proxy = True


class YoungStudentManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(age__lt=18)


class YoungStudent(Student):
    object = YoungStudentManager()

    class Meta:
        proxy = True

Task4_1_app/views.py
from django.shortcuts import render
from .models import Teacher, ClassDetails, Student, AdultStudent, YoungStudent


def home(request):
    return render(request, 'home.html', {'home': home})


def teacher(request):
    teachers = Teacher.objects.all()
    return render(request, 'teachers.html', {'teachers': teachers})


def class_detail(request):
    class_details = ClassDetails.objects.all()
    return render(request, 'class_details.html', {'class_details': class_details})


def student(request):
    students = Student.objects.all()
    return render(request, 'students.html', {'students': students})


def adult_student(request):
    adult_students = AdultStudent.object.all()
    return render(request, 'adult_students.html', {'adult_students': adult_students})


def young_student(request):
    young_students = YoungStudent.object.all()
    return render(request, 'young_students.html', {'young_students': young_students})

templates/adult_students.html
{% extends 'base/base.html' %}

{% block title %}Adult students{% endblock %}

{% block content %}
    <h1>List of Adult students</h1>
    <table>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Age</th>
            <th>Class details</th>
            <th>Attendance</th>
        </tr>
        {% for adult_student in adult_students %}
        <tr>
            <td>{{ adult_student.first_name }}</td>
            <td>{{ adult_student.last_name }}</td>
            <td>{{ adult_student.age }}</td>
            <td>{{ adult_student.class_details }}</td>
            <td>{{ adult_student.attendance }}</td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="3">No Adult students found.</td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Centered Navbar</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>

    <nav class="navbar">
        <ul>
            <li><a href="{% url 'app:home' %}">Home</a></li>
            <li><a href="{% url 'app:students' %}">Students</a></li>
            <li><a href="{% url 'app:teachers' %}">Teachers</a></li>
            <li><a href="{% url 'app:class_details' %}">Class details</a></li>
            <li><a href="{% url 'app:adult_students' %}">Adult students</a></li>
            <li><a href="{% url 'app:young_students' %}">Young students</a></li>
        </ul>
    </nav>
    
    {% block content %}
        <div class="content">
            <h1>Welcome to the Website</h1>
            <p>This is a basic template with a centered navbar.</p>
        </div>
    {% endblock %}

</body>
</html>

templates/class_details.html
{% extends 'base/base.html' %}

{% block title %}Class details{% endblock %}

{% block content %}
    <h1>List of Class details</h1>
    <table>
        <tr>
            <th>Name</th>
            <th>Teacher</th>
        </tr>
        {% for class_detail in class_details %}
        <tr>
            <td>{{ class_detail.name }}</td>
            <td>{{ class_detail.teacher }}</td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="3">No Class details found.</td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}

templates/home.html
{% extends 'base/base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    <h1>Home page</h1>
{% endblock %}

templates/students.html
{% extends 'base/base.html' %}

{% block title %}Students{% endblock %}

{% block content %}
    <h1>List of Students</h1>
    <table>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Age</th>
            <th>Class details</th>
            <th>Attendance</th>
        </tr>
        {% for student in students %}
        <tr>
            <td>{{ student.first_name }}</td>
            <td>{{ student.last_name }}</td>
            <td>{{ student.age }}</td>
            <td>{{ student.class_details }}</td>
            <td>{{ student.attendance }}</td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="3">No students found.</td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}

templates/teachers.html
{% extends 'base/base.html' %}

{% block title %}Teachers{% endblock %}

{% block content %}
    <h1>List of Teachers</h1>
    <table>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Subject</th>
        </tr>
        {% for teacher in teachers %}
        <tr>
            <td>{{ teacher.first_name }}</td>
            <td>{{ teacher.last_name }}</td>
            <td>{{ teacher.subject }}</td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="3">No teacher found.</td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}

templates/young_students.html
{% extends 'base/base.html' %}

{% block title %}Young students{% endblock %}

{% block content %}
    <h1>List of Young students</h1>
    <table>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Age</th>
            <th>Class details</th>
            <th>Attendance</th>
        </tr>
        {% for young_student in young_students %}
        <tr>
            <td>{{ young_student.first_name }}</td>
            <td>{{ young_student.last_name }}</td>
            <td>{{ young_student.age }}</td>
            <td>{{ young_student.class_details }}</td>
            <td>{{ young_student.attendance }}</td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="3">No Young students found.</td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}